project:
  type: website
  output-dir: docs

website:
  title: "Twitter als politisches System"
  sidebar:
    style: "docked"
    search: true
    contents:
    - section: "Home"
      contents:
        - index.qmd
    - section: "Über diese Seite"
      contents:
        - about.qmd
    - section: "Visualisierungen"
      contents:
        - 001_Testgraphik.qmd
  search:
    location: sidebar
    type: textbox

format:
  html:
    theme:
      dark: darkly
      light: flatly

    css: styles.css
    toc: true



