project:
  type: website
  output-dir: docs

website:
  title: "Twitter als politisches System"
  sidebar:
    style: "docked"
    search: true
    contents:
    - section: "Home"
      contents:
        - index.qmd
    - section: "Über diese Seite"
      contents:
        - about.qmd
    - section: "Erläuterungen: Daten und Methodik"
      contents:
        - datenteil_erlaeuterungen.qmd
        - methodik_erlaeuterungen.qmd
    - section: "Visualisierungen"
      contents:
        - 001_Testgraphik.qmd
  search:
    location: sidebar
    type: textbox

format:
  html:
    lang: "de"
    fontsize: "13"
    monofont: "PT Mono"
    mainfont: "Clear Sans"
    theme: lux
    css: styles.css
    toc: true



